Repository HalaAli2020/SeniorProject, pull requests merged in 2020-02, with the labels that each got.

#13 Pull posts from Firebase and New Post Fragment.
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/java/com/example/seniorproject/Auth/AuthListener.kt
  app/src/main/java/com/example/seniorproject/Auth/Auth_view_model.kt
  app/src/main/java/com/example/seniorproject/Auth/Authviewmodelfactory.kt
  app/src/main/java/com/example/seniorproject/Authentication/PasswordResetActivity.kt
  app/src/main/java/com/example/seniorproject/Authentication/RegisterActivity.kt
  app/src/main/java/com/example/seniorproject/DataListener.kt
  app/src/main/java/com/example/seniorproject/DataLoadListener.kt
  app/src/main/java/com/example/seniorproject/InjectorUtils.kt
  app/src/main/java/com/example/seniorproject/MainForum/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/HomeFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
  app/src/main/java/com/example/seniorproject/MainForum/NewPostFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Post_details.kt
  app/src/main/java/com/example/seniorproject/Utils/PostListener.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/Firebase_Repository.kt
  app/src/main/java/com/example/seniorproject/data/Post.kt
  app/src/main/java/com/example/seniorproject/data/models/Post.kt
  app/src/main/java/com/example/seniorproject/data/models/PostLive.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/utils/ViewUtils.kt
  app/src/main/java/com/example/seniorproject/viewModels/HomeFragmentViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/HomeFragmentViewModelFactory.kt
  app/src/main/java/com/example/seniorproject/viewModels/NewPostFragmentViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/NewPostFragmentViewModelFactory.kt
  app/src/main/java/com/example/seniorproject/viewModels/PostViewModel.kt
  app/src/main/res/layout/activity_post_details.xml
  app/src/main/res/layout/content_post_details.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/new_post_fragment.xml
  app/src/main/res/layout/post_rv.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#20 Added OnClick for Posts and edited UI.
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/seniorproject/MainForum/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/HomeFragment.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
  app/src/main/res/drawable/edittext_bottom_border.xml
  app/src/main/res/layout/activity_clicked_post.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/new_post_fragment.xml
Labels: enhancement

#23 Added List RecylerView.
  .idea/codeStyles/Project.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/seniorproject/Authentication/LoginActivity.kt
  app/src/main/java/com/example/seniorproject/InjectorUtils.kt
  app/src/main/java/com/example/seniorproject/MainForum/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/MainForum/HomeFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/ListAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/ListFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/NewPostFragment.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/models/Post.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/CommunityPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/CommunityPostViewModelFactory.kt
  app/src/main/java/com/example/seniorproject/viewModels/ListViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/ListViewModelFactory.kt
  app/src/main/java/com/example/seniorproject/viewModels/NewPostFragmentViewModel.kt
  app/src/main/res/drawable/bottom_navigation_selected.xml
  app/src/main/res/drawable/rounded_btn.xml
  app/src/main/res/layout/activity_community_posts.xml
  app/src/main/res/layout/activity_main_forum.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_list.xml
  app/src/main/res/layout/list_rv.xml
  app/src/main/res/layout/new_post_fragment.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#25 Made UI improvements to navigation drawer
  app/src/main/java/com/example/seniorproject/MainForum/ClickedPost.kt
  app/src/main/res/drawable/all_classes_24dp.xml
  app/src/main/res/drawable/ic_exit_to_app_black_24dp.xml
  app/src/main/res/drawable/ic_log_out.xml
  app/src/main/res/layout/activity_main_forum.xml
  app/src/main/res/layout/side_nav_header.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/values/dimens.xml
Labels: enhancement

#26 add_profileimage_to_nav
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/models/User.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/data/repositories/UserAuthRepo.kt
  app/src/main/java/com/example/seniorproject/viewModels/AuthenticationViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/HomeFragmentViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/NewPostFragmentViewModelFactory.kt
  app/src/main/res/layout/side_nav_header.xml
Labels: UI Change, bug, enhancement

#27 Merge branch 'master' into add_profileimage_to_nav
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
Labels: bug

#29 add_profileimage_to_nav_bug_fix
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/java/com/example/seniorproject/MainForum/ListFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
  app/src/main/res/layout/side_nav_header.xml
Labels: bug

#30 post_comments_author
  app/src/main/java/com/example/seniorproject/MainForum/CommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/models/Comments.kt
  app/src/main/java/com/example/seniorproject/data/models/Post.kt
  app/src/main/java/com/example/seniorproject/viewModels/NewPostFragmentViewModel.kt
  app/src/main/res/layout/comment_rv.xml
  app/src/main/res/layout/post_rv.xml
  app/src/main/res/layout/side_nav_header.xml
  app/src/test/java/com/example/seniorproject/AuthenticationViewModelTest.kt
  app/src/test/java/com/example/seniorproject/LoginActivityTest.kt
Labels: UI Change
