Repository HalaAli2020/SeniorProject, pull requests merged in 2020-03, with the labels that each got.

#32 Main Forum Subscriptions
  .idea/codeStyles/Project.xml
  app/src/main/java/com/example/seniorproject/MainForum/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/HomeFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/ListAdapter.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/HomeFragmentViewModel.kt
Labels: UI Change, enhancement

#33 Updatednetworkcalls
  .idea/gradle.xml
  app/src/main/java/com/example/seniorproject/MainForum/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/MainForum/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/HomeFragmentViewModel.kt
Labels: Ready for Review, enhancement

#34 user_profile
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/seniorproject/Dagger/AppComponent.kt
  app/src/main/java/com/example/seniorproject/InjectorUtils.kt
  app/src/main/java/com/example/seniorproject/MainForum/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/HomeFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
  app/src/main/java/com/example/seniorproject/MainForum/UserProfileActivity.kt
  app/src/main/java/com/example/seniorproject/Utils/multibindingmodule.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/HomeFragmentViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModelFactory.kt
  app/src/main/res/layout/activity_main_forum.xml
  app/src/main/res/layout/activity_user_profile.xml
  app/src/main/res/layout/profile_rv.xml
  app/src/main/res/values/strings.xml
Labels: Ready for Review, enhancement

#37 delete_posts_comments
  .idea/codeStyles/Project.xml
  app/src/main/java/com/example/seniorproject/MainForum/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/CommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/MainForum/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/CommunityPostViewModel.kt
Labels: enhancement

#36 Small fix for click post bug on Main Fragment.
  app/src/main/java/com/example/seniorproject/MainForum/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/MainForum/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/HomeFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/UserProfileActivity.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
Labels: bug fix

#38 updated posts with master
  app/src/main/java/com/example/seniorproject/MainForum/CommunityPosts.kt
Labels: bug fix

#39 Profile Fix OnClick and ImageView Deleted
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/res/layout/rv_post.xml
Labels: UI Change, bug fix

#40 deleting posts and comments with no error! Success!
  app/src/main/java/com/example/seniorproject/MainForum/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/CommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/MainForum/CustomAdapter.kt
Labels: bug fix, enhancement

#42 Registration bug fix.
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
Labels: bug fix

#44 UI Changes
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentHome.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentList.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentNewPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentSubscriptions.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/viewModels/CommunityPostViewModel.kt
  app/src/main/res/drawable/cardview_bottom_border.xml
  app/src/main/res/layout/activity_community_posts.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/rv_list.xml
  app/src/main/res/layout/rv_post.xml
  app/src/main/res/layout/rv_subs.xml
  app/src/main/res/values/colors.xml
Labels: UI Change, bug fix, enhancement

#45 Alert Dialog and UI change for deleting posts and comments
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/res/drawable/ic_delete_24px.xml
  app/src/main/res/values/styles.xml
Labels: UI Change, enhancement

#46 Removed unused post firebase listeners.
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/HomeFragmentViewModel.kt
Labels: bug fix

#47 user_profile_onclick_username_display_bugfix
  app/src/main/java/com/example/seniorproject/MainForum/UserProfileActivity.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
Labels: bug fix

#48 UI Changes to Profile Fragment.
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/EditProfileActivity.kt
  app/src/main/java/com/example/seniorproject/MainForum/UserProfileActivity.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/res/drawable/ic_account_circle_blue_24dp.xml
  app/src/main/res/drawable/ic_settings_black_24dp.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_main_forum.xml
  app/src/main/res/layout/activity_user_profile.xml
  app/src/main/res/layout/rv_post.xml
  app/src/main/res/layout/rv_post_header.xml
  app/src/main/res/layout/side_nav_header.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/menu/profile_bottom_nav_menu.xml
  app/src/main/res/values/strings.xml
Labels: UI Change, enhancement

#49 Added Classes and Sorted Subs
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/res/values/strings.xml
Labels: UI Change, bug fix

#51 Bug fix on deleting comments and posts with comments
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/ProfileCommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfileCommentFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/models/Comments.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/CommunityPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModel.kt
Labels: bug fix

#52 community opens up when you click the name from home fragment
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
Labels: enhancement

#53 Added edit posts and comments functionality!
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/seniorproject/Dagger/AppComponent.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/ProfileCommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfileCommentFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/UpdateComment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/UpdatePost.kt
  app/src/main/java/com/example/seniorproject/Utils/ButtonClickListener.kt
  app/src/main/java/com/example/seniorproject/Utils/ProfileButton.kt
  app/src/main/java/com/example/seniorproject/Utils/SwipeHelper.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/NewPostFragmentViewModel.kt
  app/src/main/res/drawable/ic_edit_24px.xml
  app/src/main/res/layout/update_comment.xml
  app/src/main/res/layout/update_post.xml
Labels: enhancement

#54 profile image url now in database
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
Labels: enhancement

#56 Username_is_now_editable
  app/src/main/java/com/example/seniorproject/MainForum/Posts/EditProfileActivity.kt
  app/src/main/java/com/example/seniorproject/MainForum/UserProfileActivity.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/models/Comments.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModel.kt
  app/src/main/res/layout/activity_edit_profile.xml
Labels: enhancement

#57 Clicking username navigates to profile.
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/ProfileCommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentHome.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfileCommentFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/UserProfileActivity.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModel.kt
  app/src/main/res/layout/activity_user_profile.xml
Labels: bug fix, enhancement

#58 Reporting Posts
  .firebaserc
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/models/Reports.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/CommunityPostViewModel.kt
  firebase.json
  functions/.gitignore
  functions/index.js
  functions/package-lock.json
  functions/package.json
Labels: enhancement

#59 Added Messaging Feature
  .idea/codeStyles/Project.xml
  Screenshot_1583367565.png
  Screenshot_1583367584.png
  Screenshot_1583367603.png
  Screenshot_1583367605.png
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/seniorproject/Dagger/InjectorUtils.kt
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
  app/src/main/java/com/example/seniorproject/Messages/Adapters/ChatLogAdapter.kt
  app/src/main/java/com/example/seniorproject/Messages/Adapters/LatestMessageAdapter.kt
  app/src/main/java/com/example/seniorproject/Messages/Adapters/NewMessageAdapter.kt
  app/src/main/java/com/example/seniorproject/Messages/ChatLog.kt
  app/src/main/java/com/example/seniorproject/Messages/FragmentLatestMessages.kt
  app/src/main/java/com/example/seniorproject/Messages/NewMessage.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/models/ChatMessage.kt
  app/src/main/java/com/example/seniorproject/data/models/LatestMessage.kt
  app/src/main/java/com/example/seniorproject/data/models/User.kt
  app/src/main/java/com/example/seniorproject/data/repositories/MessagesRepo.kt
  app/src/main/java/com/example/seniorproject/viewModels/ChatLogViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/Factories/ChatLogViewModelFactory.kt
  app/src/main/java/com/example/seniorproject/viewModels/Factories/MessagesFragmentViewModelFactory.kt
  app/src/main/java/com/example/seniorproject/viewModels/Factories/NewMessageViewModelFactory.kt
  app/src/main/java/com/example/seniorproject/viewModels/MessagesFragmentViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/NewMessageViewModel.kt
  app/src/main/res/drawable/ic_open_in_new_black_24dp.xml
  app/src/main/res/drawable/main_chat_background.xml
  app/src/main/res/drawable/round_received_message.xml
  app/src/main/res/drawable/round_send_message.xml
  app/src/main/res/drawable/rounded_sent_text.xml
  app/src/main/res/layout/m_activity_chat_log.xml
  app/src/main/res/layout/m_activity_new_message.xml
  app/src/main/res/layout/m_fragment_latest_messages.xml
  app/src/main/res/layout/m_rv_chat_from_row.xml
  app/src/main/res/layout/m_rv_chat_to_row.xml
  app/src/main/res/layout/m_rv_latest_message.xml
  app/src/main/res/layout/m_rv_new_message.xml
  app/src/main/res/menu/fragment_new_message_menu.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/strings.xml
Labels: UI Change, enhancement

#60 bio
  .idea/codeStyles/Project.xml
  app/src/main/ic_image_post_icon-web.png
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfileCommentFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/EditProfileActivity.kt
  app/src/main/java/com/example/seniorproject/MainForum/UserProfileActivity.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModel.kt
  app/src/main/res/drawable/ic_image_post_icon_foreground.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_user_profile.xml
  app/src/main/res/mipmap-anydpi-v26/ic_image_post_icon.xml
  app/src/main/res/mipmap-anydpi-v26/ic_image_post_icon_round.xml
  app/src/main/res/mipmap-hdpi/ic_image_post_icon.png
  app/src/main/res/mipmap-hdpi/ic_image_post_icon_round.png
  app/src/main/res/mipmap-mdpi/ic_image_post_icon.png
  app/src/main/res/mipmap-mdpi/ic_image_post_icon_round.png
  app/src/main/res/mipmap-xhdpi/ic_image_post_icon.png
  app/src/main/res/mipmap-xhdpi/ic_image_post_icon_round.png
  app/src/main/res/mipmap-xxhdpi/ic_image_post_icon.png
  app/src/main/res/mipmap-xxhdpi/ic_image_post_icon_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_image_post_icon.png
  app/src/main/res/mipmap-xxxhdpi/ic_image_post_icon_round.png
  app/src/main/res/values/ic_image_post_icon_background.xml
Labels: bug fix, enhancement

#61 Added reporting comments feature. Fixed bug
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
Labels: bug fix, enhancement

#62 Created date/timestamps for posts and comments.
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/ProfileCommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/models/Comments.kt
  app/src/main/java/com/example/seniorproject/data/models/Post.kt
  app/src/main/res/layout/rv_post.xml
  app/src/main/res/layout/rv_post_comment.xml
Labels: enhancement

#65 Fixed bug in adding posts/comments and fixed format of timestamp
  .idea/misc.xml
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/models/Comments.kt
  app/src/main/java/com/example/seniorproject/data/models/Post.kt
  app/src/main/res/layout/rv_post.xml
  app/src/main/res/layout/rv_post_comment.xml
  app/src/main/res/layout/rv_post_header.xml
Labels: UI Change, bug fix

#66 Fixed bug in timestamps for all posts
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/models/Post.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/NewPostFragmentViewModel.kt
Labels: bug fix

#67 UI Changes including Formatting and Drawable Change.
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/seniorproject/MainForum/Posts/EditProfileActivity.kt
  app/src/main/java/com/example/seniorproject/MainForum/UserProfileActivity.kt
  app/src/main/java/com/example/seniorproject/data/models/Comments.kt
  app/src/main/java/com/example/seniorproject/data/models/Post.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/SubscriptionsViewModel.kt
  app/src/main/res/drawable/ic_account_circle_black_24dp.xml
  app/src/main/res/drawable/send_comment_background.xml
  app/src/main/res/layout/activity_clicked_post.xml
  app/src/main/res/layout/activity_community_posts.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main_forum.xml
  app/src/main/res/layout/activity_password_reset.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_user_profile.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_list.xml
  app/src/main/res/layout/fragment_new_post.xml
  app/src/main/res/layout/fragment_profile__post.xml
  app/src/main/res/layout/fragment_profile_comment.xml
  app/src/main/res/layout/fragment_subscriptions.xml
  app/src/main/res/layout/m_activity_chat_log.xml
  app/src/main/res/layout/m_activity_new_message.xml
  app/src/main/res/layout/m_fragment_latest_messages.xml
  app/src/main/res/layout/m_rv_chat_from_row.xml
  app/src/main/res/layout/m_rv_chat_to_row.xml
  app/src/main/res/layout/m_rv_latest_message.xml
  app/src/main/res/layout/m_rv_new_message.xml
  app/src/main/res/layout/rv_list.xml
  app/src/main/res/layout/rv_post.xml
  app/src/main/res/layout/rv_post_comment.xml
  app/src/main/res/layout/rv_post_header.xml
  app/src/main/res/layout/rv_subs.xml
  app/src/main/res/layout/update_comment.xml
  app/src/main/res/layout/update_post.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: UI Change

#69 Added clickable class tag and made comments clickable
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/ProfileCommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/Utils/Callback.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/res/layout/rv_post_comment.xml
Labels: UI Change

#71 Email_Verification
  .idea/misc.xml
  app/src/main/java/com/example/seniorproject/Authentication/LoginActivity.kt
  app/src/main/java/com/example/seniorproject/Authentication/RegisterActivity.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfileCommentFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
Labels: enhancement

#74 Blocking User functionality complete.
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/CommunityPostViewModel.kt
Labels: enhancement

#81 Updatednetworkcalls
  .idea/codeStyles/Project.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/seniorproject/Dagger/AppComponent.kt
  app/src/main/java/com/example/seniorproject/Dagger/InjectorUtils.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/ProfileCommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/SubsriptionAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentHome.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentSubscriptions.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfileCommentFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/models/PostViewHolder.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/data/repositories/SearchRepo.kt
  app/src/main/java/com/example/seniorproject/search/SearchAdapter.kt
  app/src/main/java/com/example/seniorproject/search/SearchViewHolder.kt
  app/src/main/java/com/example/seniorproject/search/Search_Activity.kt
  app/src/main/java/com/example/seniorproject/viewModels/Factories/SearchViewModelFactory.kt
  app/src/main/java/com/example/seniorproject/viewModels/ListViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/SearchViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/SubscriptionsViewModel.kt
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/side_nav_header.xml
  app/src/main/res/menu/search_top_nav_menu.xml
Labels: UI Change, bug fix, enhancement

#83 Fixed click on comment bug
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/ProfileCommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Settings.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModel.kt
  app/src/main/res/layout/activity_settings.xml
Labels: bug fix

#86 UI Fixes to Messaging, Main Forum Image Posts, and Profile
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/seniorproject/MainForum/NewPost/FragmentNewPost.kt
  app/src/main/java/com/example/seniorproject/Messages/Adapters/LatestMessageAdapter.kt
  app/src/main/java/com/example/seniorproject/Messages/FragmentLatestMessages.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/MessagesRepo.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/NewPostFragmentViewModel.kt
  app/src/main/res/layout/activity_user_profile.xml
  app/src/main/res/layout/m_rv_latest_message.xml
  app/src/main/res/layout/side_nav_header.xml
Labels: UI Change, bug fix

#87 Fixed bug in comments in user profile.
  .idea/codeStyles/Project.xml
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/ProfileCommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/res/layout/rv_post_image.xml
Labels: bug fix

#88 Real time email and bio + bug fixes
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentHome.kt
  app/src/main/java/com/example/seniorproject/MainForum/UserProfileActivity.kt
  app/src/main/java/com/example/seniorproject/Utils/EmailCallback.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModel.kt
  app/src/main/res/layout/activity_user_profile.xml
Labels: bug fix, enhancement

#89 Updatednetworkcalls
  .idea/codeStyles/Project.xml
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentHome.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentSubscriptions.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/SubscriptionsViewModel.kt
  app/src/main/res/layout/activity_edit_profile.xml
Labels: UI Change, bug fix

#90 UISTUFF
  app/src/main/java/com/example/seniorproject/Authentication/LoginActivity.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/Messages/Adapters/NewMessageAdapter.kt
  app/src/main/res/layout/activity_search.xml
Labels: LGTM, UI Change, bug fix

#91 Bug fixed in image profile of other users
  .idea/codeStyles/Project.xml
  app/src/main/java/com/example/seniorproject/MainForum/UserProfileActivity.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/models/User.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModel.kt
Labels: bug fix

#92 Coroutines for Login, Register, and Reset Password Complete!
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/UserAuthRepo.kt
  app/src/main/java/com/example/seniorproject/viewModels/AuthenticationViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_password_reset.xml
  app/src/main/res/layout/activity_register.xml
Labels: LGTM, enhancement

#95 Fixed bug in error handling for register, login, and reset password bug fix
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/UserAuthRepo.kt
  app/src/main/java/com/example/seniorproject/viewModels/AuthenticationViewModel.kt
  app/src/test/java/com/example/seniorproject/AuthenticationViewModelTest.kt
Labels: bug fix
