Repository HalaAli2020/SeniorProject, pull requests merged in 2020-04, with the labels that each got.

#97 Added Search to new messages
  app/build.gradle
  app/src/main/java/com/example/seniorproject/Authentication/RegisterActivity.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/ProfileCommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfileCommentFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/NewPost/FragmentNewImagePost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Settings.kt
  app/src/main/java/com/example/seniorproject/Messages/Adapters/NewMessageAdapter.kt
  app/src/main/java/com/example/seniorproject/Messages/NewMessage.kt
  app/src/main/java/com/example/seniorproject/data/models/LatestMessage.kt
  app/src/main/java/com/example/seniorproject/search/Search_Activity.kt
  app/src/main/java/com/example/seniorproject/viewModels/HomeFragmentViewModel.kt
  app/src/main/res/layout/m_activity_new_message.xml
Labels: UI Change, enhancement

#98 no_comments/posts_bug
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/ProfileCommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentHome.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfileCommentFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
  app/src/main/java/com/example/seniorproject/MainForum/NewPost/FragmentNewImagePost.kt
  app/src/main/java/com/example/seniorproject/MainForum/UserProfileActivity.kt
  app/src/main/java/com/example/seniorproject/Utils/checkCallback.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/MessagesRepo.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/data/repositories/SearchRepo.kt
  app/src/main/java/com/example/seniorproject/data/repositories/UserAuthRepo.kt
  app/src/main/java/com/example/seniorproject/viewModels/AuthenticationViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/ChatLogViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/CommunityPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/HomeFragmentViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/ListViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/NewPostFragmentViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/SearchViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/SubscriptionsViewModel.kt
Labels: bug fix

#101 Kotlin Flow Real-time updates on Posts
  app/build.gradle
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/PostAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/Messages/FragmentLatestMessages.kt
  app/src/main/java/com/example/seniorproject/Utils/FlowCallback.kt
  app/src/main/java/com/example/seniorproject/Utils/MutableListCallback.kt
  app/src/main/java/com/example/seniorproject/Utils/ViewUtils.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/CommunityPostViewModel.kt
Labels: enhancement

#102 Real-time Updates on Comments
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsListAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/CommunityPostViewModel.kt
Labels: enhancement

#103 Revert "Real-time Updates on Comments"
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsListAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/CommunityPostViewModel.kt
Labels: invalid

#105 Real-time updates for Comments Complete!
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsListAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
Labels: LGTM, enhancement

#106 block_users_bug
  .idea/misc.xml
  app/src/main/java/com/example/seniorproject/Dagger/DataListener.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsListAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/PostAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/ProfileCommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfileCommentFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/EditProfileActivity.kt
  app/src/main/java/com/example/seniorproject/MainForum/UserProfileActivity.kt
  app/src/main/java/com/example/seniorproject/Messages/Adapters/ChatLogAdapter.kt
  app/src/main/java/com/example/seniorproject/Utils/MutableListCallback.kt
  app/src/main/java/com/example/seniorproject/Utils/SwipeHelper.kt
  app/src/main/java/com/example/seniorproject/Utils/ViewUtils.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/models/CommentLive.kt
  app/src/main/java/com/example/seniorproject/data/models/Comments.kt
  app/src/main/java/com/example/seniorproject/data/models/PostLive.kt
  app/src/main/java/com/example/seniorproject/data/models/User.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/search/SearchAdapter.kt
  app/src/main/java/com/example/seniorproject/search/Search_Activity.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/CommunityPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/ListViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/SearchViewModel.kt
Labels: bug fix

#107 Profile Bug Fix
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/ProfileCommentsAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/NewPost/FragmentNewImagePost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/EditProfileActivity.kt
  app/src/main/java/com/example/seniorproject/MainForum/UserProfileActivity.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModel.kt
  app/src/main/res/layout/activity_edit_profile.xml
Labels: bug fix, documentation

#109 Post profile bug fix.
  app/src/main/java/com/example/seniorproject/MainForum/UserProfileActivity.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
Labels: bug fix

#110 Bug fix on Clicked Post and Profile Comments in Real-time
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsListAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/ProfileCommAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfileCommentFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
  app/src/main/java/com/example/seniorproject/MainForum/NewPost/FragmentNewImagePost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/EditProfileActivity.kt
  app/src/main/java/com/example/seniorproject/MainForum/Settings.kt
  app/src/main/java/com/example/seniorproject/MainForum/UserProfileActivity.kt
  app/src/main/java/com/example/seniorproject/Messages/Adapters/LatestMessageAdapter.kt
  app/src/main/java/com/example/seniorproject/Messages/Adapters/NewMessageAdapter.kt
  app/src/main/java/com/example/seniorproject/Messages/NewMessage.kt
  app/src/main/java/com/example/seniorproject/Utils/ViewUtils.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/models/Comments.kt
  app/src/main/java/com/example/seniorproject/data/models/LatestMessage.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/CommunityPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModel.kt
Labels: bug fix, enhancement

#111 post and comment validation bug fixes
  app/src/main/java/com/example/seniorproject/MainForum/NewPost/FragmentNewImagePost.kt
  app/src/main/java/com/example/seniorproject/MainForum/NewPost/FragmentNewPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/NewPost/NewPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/NewPostFragmentViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/SubscriptionsViewModel.kt
  app/src/main/res/layout/fragment_new_post.xml
Labels: bug fix, documentation

#112 Report Users, Comments Bug Fixes
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
Labels: bug fix, documentation

#113 Home Fragment Coroutines
  app/build.gradle
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/Homeadapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentHome.kt
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/interfaces/FirebaseInterfaces.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/data/repositories/SearchRepo.kt
  app/src/main/java/com/example/seniorproject/search/Search_Activity.kt
  app/src/main/java/com/example/seniorproject/viewModels/HomeFragmentViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/SearchViewModel.kt
  app/src/main/res/layout/activity_search.xml
Labels: UI Change, enhancement

#114 Added Coroutines to User Posts and Edited Model Functions
  .idea/codeStyles/Project.xml
  UnitLogo.psd
  UnitLogoProper.png
  UnitLogoProperNav.png
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/Homeadapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/PostAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/ProfileCommAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfileCommentFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/models/Comments.kt
  app/src/main/java/com/example/seniorproject/data/models/Post.kt
  app/src/main/java/com/example/seniorproject/data/models/PostViewHolder.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/data/repositories/SearchRepo.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/CommunityPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#115 Fixed comments bug in clicked post
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModel.kt
  app/src/main/res/layout/activity_clicked_post.xml
Labels: bug fix

#116 Blocked_user_bugfix_comments_and_warnings
  app/src/main/java/com/example/seniorproject/Authentication/LoginActivity.kt
  app/src/main/java/com/example/seniorproject/Authentication/PasswordResetActivity.kt
  app/src/main/java/com/example/seniorproject/Authentication/RegisterActivity.kt
  app/src/main/java/com/example/seniorproject/Dagger/InjectorUtils.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsListAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/Homeadapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/PostAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/SubsriptionAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentHome.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentList.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentSubscriptions.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfileCommentFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
  app/src/main/java/com/example/seniorproject/MainForum/NewPost/FragmentNewImagePost.kt
  app/src/main/java/com/example/seniorproject/MainForum/NewPost/FragmentNewPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/EditProfileActivity.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/UpdateComment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/UpdatePost.kt
  app/src/main/java/com/example/seniorproject/MainForum/UserProfileActivity.kt
  app/src/main/java/com/example/seniorproject/Messages/ChatLog.kt
  app/src/main/java/com/example/seniorproject/Messages/FragmentLatestMessages.kt
  app/src/main/java/com/example/seniorproject/Messages/NewMessage.kt
  app/src/main/java/com/example/seniorproject/Utils/multibindingmodule.kt
  app/src/main/java/com/example/seniorproject/search/SearchViewHolder.kt
Labels: bug fix, documentation, enhancement

#117 comments toast messages fixed
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
  app/src/main/res/layout/activity_clicked_post.xml
Labels: bug fix, documentation

#118 Added Comments moved all interfaces to interface file and deleted som…
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfileCommentFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/interfaces/FirebaseInterfaces.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/data/repositories/SearchRepo.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/HomeFragmentViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/NewPostFragmentViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/SearchViewModel.kt
Labels: bug fix, documentation, enhancement

#119 Code clean up
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/interfaces/FirebaseInterfaces.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/search/SearchAdapter.kt
  app/src/main/java/com/example/seniorproject/search/SearchViewHolder.kt
  app/src/main/java/com/example/seniorproject/search/Search_Activity.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModel.kt
Labels: Ready for Review, enhancement

#120 Bug fix on profile page and swiping is back!
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfileCommentFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModel.kt
Labels: bug fix

#121 Added Comments, deleted dead code, and refactored factories
  app/src/main/java/com/example/seniorproject/Dagger/AppComponent.kt
  app/src/main/java/com/example/seniorproject/Dagger/InjectorUtils.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CustomAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/PostAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/SubscriptionAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentHome.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentList.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentSubscriptions.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfileCommentFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/EditProfileActivity.kt
  app/src/main/java/com/example/seniorproject/MainForum/UserProfileActivity.kt
  app/src/main/java/com/example/seniorproject/Messages/ChatLog.kt
  app/src/main/java/com/example/seniorproject/Messages/FragmentLatestMessages.kt
  app/src/main/java/com/example/seniorproject/Messages/NewMessage.kt
  app/src/main/java/com/example/seniorproject/Utils/ButtonClickListener.kt
  app/src/main/java/com/example/seniorproject/Utils/ProfileButton.kt
  app/src/main/java/com/example/seniorproject/Utils/SwipeHelper.kt
  app/src/main/java/com/example/seniorproject/Utils/ViewUtils.kt
  app/src/main/java/com/example/seniorproject/Utils/multibindingmodule.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/interfaces/FirebaseInterfaces.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/search/Search_Activity.kt
  app/src/main/java/com/example/seniorproject/viewModels/Factories/ChatLogViewModelFactory.kt
  app/src/main/java/com/example/seniorproject/viewModels/Factories/CommunityPostViewModelFactory.kt
  app/src/main/java/com/example/seniorproject/viewModels/Factories/HomeFragmentViewModelFactory.kt
  app/src/main/java/com/example/seniorproject/viewModels/Factories/ListViewModelFactory.kt
  app/src/main/java/com/example/seniorproject/viewModels/Factories/MessagesFragmentViewModelFactory.kt
  app/src/main/java/com/example/seniorproject/viewModels/Factories/NewMessageViewModelFactory.kt
  app/src/main/java/com/example/seniorproject/viewModels/Factories/ProfileViewModelFactory.kt
  app/src/main/java/com/example/seniorproject/viewModels/Factories/SearchViewModelFactory.kt
  app/src/main/java/com/example/seniorproject/viewModels/Factories/SubscriptionsViewModelFactory.kt
Labels: LGTM, bug fix, documentation

#123 Added more comments and deleted more unused files
  app/src/main/java/com/example/seniorproject/Authentication/LoginActivity.kt
  app/src/main/java/com/example/seniorproject/Authentication/PasswordResetActivity.kt
  app/src/main/java/com/example/seniorproject/Authentication/RegisterActivity.kt
  app/src/main/java/com/example/seniorproject/Dagger/SeniorProjApp.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentHome.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentList.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/EditProfileActivity.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/UpdateComment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/UpdatePost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Settings.kt
  app/src/main/java/com/example/seniorproject/MainForum/UserProfileActivity.kt
  app/src/main/java/com/example/seniorproject/Utils/FlowCallback.kt
  app/src/main/java/com/example/seniorproject/Utils/MutableListCallback.kt
  app/src/main/java/com/example/seniorproject/Utils/ProfileButton.kt
  app/src/main/java/com/example/seniorproject/Utils/SwipeHelper.kt
  app/src/main/java/com/example/seniorproject/data/interfaces/FirebaseInterfaces.kt
  app/src/main/java/com/example/seniorproject/data/models/CommentLive.kt
  app/src/main/java/com/example/seniorproject/data/models/PostLive.kt
  app/src/main/java/com/example/seniorproject/data/models/PostViewHolder.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/CommunityPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/Factories/DaggerViewModelFactory.kt
  app/src/main/java/com/example/seniorproject/viewModels/HomeFragmentViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/ListViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/SubscriptionsViewModel.kt
Labels: documentation

#124 Added Comments to Messaging and Editing UI Changes
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/seniorproject/MainForum/NewPost/NewPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/EditProfileActivity.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/UpdateComment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/UpdatePost.kt
  app/src/main/java/com/example/seniorproject/Messages/Adapters/ChatLogAdapter.kt
  app/src/main/java/com/example/seniorproject/Messages/Adapters/LatestMessageAdapter.kt
  app/src/main/java/com/example/seniorproject/Messages/Adapters/NewMessageAdapter.kt
  app/src/main/java/com/example/seniorproject/Messages/ChatLog.kt
  app/src/main/java/com/example/seniorproject/Messages/FragmentLatestMessages.kt
  app/src/main/java/com/example/seniorproject/Messages/NewMessage.kt
  app/src/main/java/com/example/seniorproject/search/SearchAdapter.kt
  app/src/main/java/com/example/seniorproject/search/SearchViewHolder.kt
  app/src/main/java/com/example/seniorproject/search/Search_Activity.kt
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_user_profile.xml
  app/src/main/res/layout/update_comment.xml
  app/src/main/res/layout/update_post.xml
  app/src/main/res/values/strings.xml
Labels: UI Change, documentation

#125 toast_messages_and_warnings
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/seniorproject/Authentication/LoginActivity.kt
  app/src/main/java/com/example/seniorproject/Authentication/PasswordResetActivity.kt
  app/src/main/java/com/example/seniorproject/Authentication/RegisterActivity.kt
  app/src/main/java/com/example/seniorproject/Dagger/SeniorProjApp.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsListAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/Homeadapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/PostAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/ProfileCommAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentHome.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentSubscriptions.kt
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
  app/src/main/java/com/example/seniorproject/MainForum/NewPost/FragmentNewImagePost.kt
  app/src/main/java/com/example/seniorproject/MainForum/NewPost/FragmentNewPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/NewPost/NewPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/UpdateComment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/UpdatePost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Settings.kt
  app/src/main/java/com/example/seniorproject/Messages/Adapters/NewMessageAdapter.kt
  app/src/main/java/com/example/seniorproject/Messages/ChatLog.kt
  app/src/main/java/com/example/seniorproject/Utils/SwipeHelper.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/interfaces/FirebaseInterfaces.kt
  app/src/main/java/com/example/seniorproject/data/models/Comments.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/data/repositories/SearchRepo.kt
  app/src/main/java/com/example/seniorproject/search/SearchAdapter.kt
  app/src/main/java/com/example/seniorproject/viewModels/ChatLogViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/ClickedPostViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/HomeFragmentViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/NewPostFragmentViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/ProfileViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/SearchViewModel.kt
  app/src/main/res/drawable-hdpi/app_logo.png
  app/src/main/res/drawable-mdpi/app_logo.png
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable-xhdpi/app_logo.png
  app/src/main/res/drawable-xxhdpi/app_logo.png
  app/src/main/res/drawable-xxxhdpi/app_logo.png
  app/src/main/res/drawable/ic_delete_24px.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_menu_black_24dp.xml
  app/src/main/res/drawable/rounded_images.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_user_profile.xml
  app/src/main/res/menu/search_top_nav_menu.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/ic_add_photo.xml
  app/src/main/res/values/strings.xml
Labels: bug fix

#126 Bug fix on blocking in database and restart profile
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfileCommentFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
Labels: bug fix

#127 Added unblock user feature
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/seniorproject/Dagger/AppComponent.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/BlockedUsersAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsListAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/PostAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/ProfileCommAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/MainForum/UnblockUserActivity.kt
  app/src/main/java/com/example/seniorproject/Utils/multibindingmodule.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/interfaces/FirebaseInterfaces.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/Factories/SettingsViewModelFactory.kt
  app/src/main/java/com/example/seniorproject/viewModels/SettingsViewModel.kt
  app/src/main/res/drawable/ic_block_black_24dp.xml
  app/src/main/res/layout/activity_unblock_users.xml
  app/src/main/res/layout/rv_unblock_users.xml
  app/src/main/res/menu/activity_main_drawer.xml
Labels: enhancement

#128 unblock converted to swipe
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/BlockedUsersAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/UnblockUserActivity.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/SettingsViewModel.kt
  app/src/main/res/layout/rv_unblock_users.xml
Labels: UI Change, enhancement

#129 add_swipe_to_unblock
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/UnblockUserActivity.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/SettingsViewModel.kt
Labels: bug fix

#130 ChatLog Fix. Editing Posts and Comments Fix. Messaging Profile Images.
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentHome.kt
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/EditProfileActivity.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/UpdateComment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/UpdatePost.kt
  app/src/main/java/com/example/seniorproject/Messages/Adapters/LatestMessageAdapter.kt
  app/src/main/java/com/example/seniorproject/Messages/Adapters/NewMessageAdapter.kt
  app/src/main/java/com/example/seniorproject/Messages/ChatLog.kt
  app/src/main/java/com/example/seniorproject/Messages/FragmentLatestMessages.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/models/ChatMessage.kt
  app/src/main/java/com/example/seniorproject/data/models/LatestMessage.kt
  app/src/main/java/com/example/seniorproject/data/repositories/MessagesRepo.kt
  app/src/main/java/com/example/seniorproject/viewModels/ChatLogViewModel.kt
  app/src/main/res/layout/m_activity_chat_log.xml
  app/src/main/res/layout/m_rv_chat_from_row.xml
  app/src/main/res/layout/m_rv_chat_to_row.xml
  app/src/main/res/layout/update_comment.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: UI Change, bug fix

#131 Bug Fixes to Intent and UI.
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/BlockedUsersAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfileCommentFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/UpdateComment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/UpdatePost.kt
  app/src/main/java/com/example/seniorproject/MainForum/UnblockUserActivity.kt
  app/src/main/res/layout/activity_clicked_post.xml
  app/src/main/res/layout/activity_unblock_users.xml
  app/src/main/res/layout/fragment_new_post.xml
  app/src/main/res/layout/m_rv_latest_message.xml
  app/src/main/res/layout/rv_unblock_users.xml
  app/src/main/res/layout/update_comment.xml
  app/src/main/res/layout/update_post.xml
Labels: UI Change, bug fix

#132 Updatednetworkcalls
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/Homeadapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentHome.kt
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/data/Firebase/FirebaseData.kt
  app/src/main/java/com/example/seniorproject/data/interfaces/FirebaseInterfaces.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/viewModels/HomeFragmentViewModel.kt
  app/src/main/java/com/example/seniorproject/viewModels/SearchViewModel.kt
Labels: UI Change, bug fix, enhancement

#133 updated uid to author in homeadapter
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/Homeadapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/PostAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfileCommentFragment.kt
  app/src/test/java/com/example/seniorproject/ExampleUnitTest.kt
Labels: bug fix

#134 Load 10 comments at a time funcitonality complete!
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsListAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/EditProfileActivity.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/res/layout/activity_clicked_post.xml
Labels: UI Change, bug fix, enhancement

#135 image bug fix in hamburger menu
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
Labels: bug fix

#136 remove_refresh
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentHome.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfileCommentFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/MainForum/UserProfileActivity.kt
  app/src/main/java/com/example/seniorproject/viewModels/HomeFragmentViewModel.kt
Labels: UI Change

#137 Added UI to Loading Comments
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/ClickedPost.kt
  app/src/main/res/layout/activity_clicked_post.xml
Labels: UI Change

#138 Caching Fix
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
Labels: bug fix

#139 Fixed extra post home fragment bug
  app/src/main/java/com/example/seniorproject/MainForum/Adapters/CommentsListAdapter.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/FragmentHome.kt
  app/src/main/java/com/example/seniorproject/MainForum/Fragments/ProfilePostFragment.kt
  app/src/main/java/com/example/seniorproject/MainForum/MainForum.kt
  app/src/main/java/com/example/seniorproject/MainForum/Posts/CommunityPosts.kt
  app/src/main/java/com/example/seniorproject/Utils/SwipeHelper.kt
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
  app/src/main/java/com/example/seniorproject/search/SearchAdapter.kt
  app/src/main/java/com/example/seniorproject/viewModels/HomeFragmentViewModel.kt
Labels: bug fix

#140 UI Changes
  app/src/main/java/com/example/seniorproject/data/models/Classes.kt
  app/src/main/res/drawable/unitlogopropernav.png
  app/src/main/res/layout/rv_list.xml
  app/src/main/res/layout/rv_post.xml
  app/src/main/res/layout/rv_post_image.xml
Labels: UI Change

#141 minor bug fix getting subscribed posts
  app/src/main/java/com/example/seniorproject/data/repositories/PostRepository.kt
Labels: bug fix

#142 UI change for imageviews and got rid of refresh
  app/src/main/res/layout/activity_community_posts.xml
  app/src/main/res/layout/fragment_profile__post.xml
  app/src/main/res/layout/fragment_profile_comment.xml
  app/src/main/res/layout/rv_list.xml
  app/src/main/res/layout/rv_post_header.xml
  app/src/main/res/layout/rv_subs.xml
Labels: UI Change, bug fix
